version: '3'
services:
  sync:
    image: 1ris/aisle-cos:latest
    volumes:
      - type: volume
        source: cfs-jbe9pl03
        target: /mnt/nfs
        volume:
          nocopy: true
volumes:
  cfs-jbe9pl03:
    driver_opts:
      type: "nfs"
      o: "addr=10.206.0.15,nolock,soft,rw"
      device: ":/u4pmuefx"
