version: '3'
services:
  sync:
    image: 1ris/aisle-cos:latest
    logging:
      driver: "json-file"
      options:
        labels: "servicename"
        tag: "{{.ImageName}}/{{.Name}}/{{.ID}}"
        max-size: "100m"
        max-file: "5"
    volumes:
      - type: volume
        source: cfs-jbe9pl03
        target: /mnt/nfs
        volume:
          nocopy: true
volumes:
  cfs-jbe9pl03:
    driver_opts:
      type: "nfs"
      o: "addr=10.206.0.15,nolock,soft,rw"
      device: ":/u4pmuefx"
